version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trungisdead1/iot-project:v1.0
    ports:
      - "3000:3000"
    environment:
      # - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=smartdoor
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: smartdoor
